package com.gcc.monopoleirb.core.squares;

public enum SquareType {

	ANY_SQUARE, DEPARTURE_SQUARE, PROPERTY_SQUARE, FIELD_SQUARE, TAX_SQUARE, CHANCE, COMMUNITY_CHEST, JAIL_SQUARE, FREE_PARK_SQUARE, PUBLIC_SERVICE_SQUARE, TRAIN_STATION_SQUARE;

}
